In [9]:
import pandas as pd

In [25]:
# Criando um dicionario 
vendas  = {
    'data':['22/05/2026','23/05/2026'],
    'valor':[500,300],
    'produto':['arroz','feijao'],
    'quantidade':[50,70]    
}

# Transformando meu dicionario venda em um data frame
vendas_df = pd.DataFrame(vendas)

In [34]:
vendas_df

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Morumbi,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Morumbi,Casaco Xadrez,4,259,1036

# Importando uma base de dados

In [32]:
# Lendo uma base de dados externa
vendas_df = pd.read_excel('Vendas.xlsx')

In [46]:
# head() exibe as primeiras linhas 
# tail exibe as ultimas linhas
vendas_df.head(3)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368

In [48]:
#shape retorna a quantidade de linhas e de colunas (linhas,colunas)
vendas_df.shape

(93910, 7)

In [50]:
# print(vendas_df.describe())

       Código Venda                           Data    Quantidade  \
count  93910.000000                          93910  93910.000000
mean   32464.762155  2019-06-16 23:52:28.265360896      2.166553
min        1.000000            2019-01-01 00:00:00      1.000000
25%    16204.000000            2019-03-26 00:00:00      1.000000
50%    32367.000000            2019-06-17 00:00:00      2.000000
75%    48793.750000            2019-09-08 00:00:00      3.000000
max    65014.000000            2019-11-30 00:00:00      5.000000
std    18809.007093                            NaN      1.258732

       Valor Unitário   Valor Final
count    93910.000000  93910.000000
mean       191.725886    414.862656
min         30.000000     30.000000
25%        100.000000    156.000000
50%        155.000000    274.000000
75%        248.000000    524.000000
max        750.000000   3750.000000
std        145.215519    434.846228

# Metodos para manipular meu data frame

In [74]:


# Acessando duas colunas do meu data frame original vendas_df
# o resultado é um data frame tambem 
df_teste = vendas_df[['Produto','Quantidade']]
type(df_teste)

pandas.core.frame.DataFrame

In [76]:

# Caso eu selecione somente uma coluna do meu data frame o resultado e uma series do pandas
produtos = vendas_df['Produto']
type(produtos)

pandas.core.series.Series

In [89]:
vendas_df.head(5)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71

In [93]:
# loc() && iloc

# Pegar somente a primeira linha 
# display(vendas_df.loc(1))


# Pegar da primeira linha ate a quinta  linha 
display(vendas_df.loc[0:4])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71

In [121]:
# Pegar linhas que correspondem a uma determinada condicao
vendas_norte_shopping_df = vendas_df.loc[  vendas_df['ID Loja'] == 'Norte Shopping' ]
# Pegar varias linhas e varias colunas usando o loc
# loc(linhas,colunas)
# Filtrando linhas e colunas
vendas_df.loc[  vendas_df['ID Loja'] == 'Norte Shopping' , ['ID Loja','Produto','Quantidade'] ]

              ID Loja                 Produto  Quantidade
3      Norte Shopping                 Relógio           3
4      Norte Shopping            Chinelo Liso           1
8      Norte Shopping  Camisa Gola V Listrado           1
9      Norte Shopping             Camisa Liso           1
100    Norte Shopping            Cueca Xadrez           5
...               ...                     ...         ...
93716  Norte Shopping             Polo Xadrez           1
93754  Norte Shopping              Calça Liso           1
93755  Norte Shopping          Casaco Estampa           2
93756  Norte Shopping                   Gorro           2
93852  Norte Shopping           Bermuda Linho           1

[3924 rows x 3 columns]

# Adicionando colunas

In [130]:
# A partir de uma coluna que existe

# vendas_df['Comissao'] = vendas_df['Valor Final'] * 0.05


# Criando uma coluna com valor padrao
# interessante entender o metodo loc(LINHAS,COLUNAS)

vendas_df.loc[ : ,'Imposto'] = 0
vendas_df.head(10)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissao,Imposto
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00,0
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55,0
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248,12.40,0
6,5,2019-01-02,Shopping Barra,Calça,1,170,170,8.50,0
7,6,2019-01-02,Shopping Ibirapuera,Polo Listrado,4,149,596,29.80,0
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116,5.80,0
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105,5.25,0

In [138]:
# Vendas de dezembro que faltavam
vendas_dez_df = pd.read_excel('Vendas - Dez.xlsx')
vendas_dez_df

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

In [146]:
vendas_df = pd.concat([vendas_df, vendas_dez_df], ignore_index=True)
vendas_df

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Comissao,Imposto
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358,17.90,0.0
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,2,180,360,18.00,0.0
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368,18.40,0.0
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600,30.00,0.0
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71,3.55,0.0
...,...,...,...,...,...,...,...,...,...
115172,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204,NaN,NaN
115173,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080,NaN,NaN
115174,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87,NaN,NaN
115175,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108,NaN,NaN
115176,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266,NaN,NaN